name: Build Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: readthedocs/build:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python dependencies
        run: pip install -e .
      - name: Install docs requirements
        run: pip install -r docs/requirements.txt
      - name: Build Sphinx docs
        run: sphinx-build -b html docs docs/_build/html
      - name: Upload built docs
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html
